### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by suphon-t** [sent44/node-twallet#1]
Why do you need to use complicated callbacks? Just returning the result is easier for developer and users.

**Comment by sent44** [comment]
Because Node.js is `Asynchronous` but this script require `Synchronous`
I don't want script fetch data before login success

**Comment by suphon-t** [comment]
I understand that as someone who writes in Node.js a lot. 
But that doesn't make sense at all since this project is not asynchronous. 
Take a look at [this](https://github.com/sent44/node-twallet/blob/master/app.js#L76)(line 76 from 01885c08f24d5b7975be10317dfaae8ad9b42a77). 
If it is really asynchronous, why would it work?

**Comment by suphon-t** [comment]
Sorry. It's just your weird indenting that is confusing me. If you are going to open source something, please make it easy to read by other people.

**Comment by sent44** [comment]
* This project require asynchronous as I said from above
* From line 76(01885c08f24d5b7975be10317dfaae8ad9b42a77) isn't about synchronous. It's intelligent from Javascript itself. At that time I found out that I cant replace with normal replacer string by forgotten reason. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* I think it short enough and some variable/function name is explain what they do itself(some is not; my bad) so I didn't put any comment to explain. I will put it later.
