### ISSUE TITLE
Where to find TrueWallet API document?

### ISSUE THREAD

**Issue by Porama6400** [sent44/node-twallet#2]
Where to find TrueWallet API document?

**Comment by Porama6400** [comment]
I mean protocol use to communicate with TrueWallet server

**Comment by sent44** [comment]
Do It Yourself
You can use Express module as your server to communicate.
This module doesn't have build-in web server for you.

**Comment by sent44** [comment]
[Here](https://github.com/sent44/node-twallet/blob/master/app.js#L10)
Sorry for my code is hard to read, I will rewrite it again when I have free time.
